lots of code to identity and flip TMCs to new symmetry groups
hjkgrp/molSimplify pull request #297
Opened 2024-12-11 00:47 UTC by jwtoney

lots of code to identity and flip TMCs to new symmetry groups

2024-12-11 17:36 UTC, gianmarco-terrones requested changes
Looks good! Can you add some brief comments around line 6376 indicating what that code does? It seems there is code there that is copy+pasted throughout the function, so it would be better to make a helper function and just call that. Also, adding a test for the new `flip_symmetry` function would also be good

Code that shows up a lot in the `flip_symmetry` function:
```
vec1 = np.array(tmc_mol.atoms[lig1_catoms[swap_idx_1]].coords()) - np.array(tmc_mol.atoms[metal_idx].coords())
vec3 = np.array(tmc_mol.atoms[lig3_catoms[swap_idx_3]].coords()) - np.array(tmc_mol.atoms[metal_idx].coords())
atoms_to_move_b = lig1_atoms[swap_idx_1] + lig3_atoms[swap_idx_3]
```
and
```
vec_reflect_b = vec1 / np.linalg.norm(vec1, 2) + vec3 / np.linalg.norm(vec3, 2)
vec_reflect_b = vec_reflect_b / np.linalg.norm(vec_reflect_b, 2)
for atom_idx in atoms_to_move_b:
    vec_atoms = np.array(tmc_mol.atoms[atom_idx].coords()) - np.array(tmc_mol.atoms[metal_idx].coords())
    vec_proj = np.dot(vec_atoms, vec_reflect_b) * vec_reflect_b
    reflected_coords = np.array(tmc_mol.atoms[metal_idx].coords()) + 2 * vec_proj - vec_atoms
    tmc_mol.atoms[atom_idx].setcoords(reflected_coords)

```

2024-12-16 20:42 UTC, aarongarrison requested changes
Looks good to me! A few small changes would be nice:

- In `get_symmetry`, if the user asks for `details`, but the structure does not have 2 or 3 unique ligands, you will run into an error. Adding in a check for this would be good.
- In `reflect_coords`, I believe that you edit the `mol3D` object passed in to the function. This may lead to unintended behavior, and I recommend using `copymol3D` instead. However, as long as you document it, this should be fine.

2025-01-14 19:33 UTC, jwtoney commented
addressed @aarongarrison 's requested changes, and extended capability to multidentate complexes

2025-01-14 20:36 UTC, aarongarrison approved these changes
Looks good to me! It may be good to move some of your helper functions out of `mol3D` and into `Scripts` or similar. Also, if you could add a comment about `reflect_coords` editing the original `mol3D`, I think that would add clarity.

2025-01-24 19:50 UTC, merged